face: intricate-anim.mdl lex.py main.py matrix.py mdl.py script.py yacc.py display.py draw.py gmath.py
	python main.py intricate-anim.mdl

clean:
	rm *pyc *out parsetab.py

clear:
	rm *pyc *out parsetab.py *ppm

test: blah.mdl lex.py main.py matrix.py mdl.py script.py yacc.py display.py draw.py gmath.py
	python main.py blah.mdl

